name = "bmselempattern"
defaultTargets = ["BmsElemPattern"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "Bm4"
globs = ["Bm4.+"]

[[lean_lib]]
name = "Pattern"
globs = ["Pattern.+"]

[[lean_lib]]
name = "BmsElemPattern"
